# SPDX-FileCopyrightText: Copyright (c) 2024 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: npm
'on':
  push:
  pull_request:
jobs:
  npm:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        java: [17]
        node: [16]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - run: npm install
    - run: npm run eslint
    - run: npm test
